services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - music_genre_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - music_genre_network

networks:
  music_genre_network:
    driver: bridge
